version: '3.8'

services:
  web:
    build: ./django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    container_name: postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-d",
          "postgres",
          "--username",
          "postgres"
        ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=donkey

volumes:
  postgres_data: